# Generated by Django 4.0.1 on 2022-01-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('head_name', models.CharField(max_length=45)),
                ('room_number', models.CharField(max_length=10)),
                ('corp_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('teachers_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('hours', models.IntegerField()),
                ('cycle', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('dean_name', models.CharField(max_length=45)),
                ('room_number', models.CharField(max_length=10)),
                ('corp_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('birth', models.IntegerField()),
                ('admission_to_work', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('post', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='facultie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.facultie'),
        ),
        migrations.CreateModel(
            name='Academic_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('groups', models.CharField(max_length=45)),
                ('students_count', models.IntegerField()),
                ('exams_type', models.CharField(max_length=45)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.teacher')),
            ],
        ),
    ]
