# Generated by Django 4.0.1 on 2022-01-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVTExample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_load',
            name='academic_year',
            field=models.CharField(max_length=45, verbose_name='Академический год'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='exams_type',
            field=models.CharField(max_length=45, verbose_name='Вид итогового контроля'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='groups',
            field=models.CharField(max_length=45, verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='students_count',
            field=models.IntegerField(verbose_name='Количество студентов'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='academic_load',
            name='term',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='department',
            name='corp_number',
            field=models.CharField(max_length=10, verbose_name='Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='department',
            name='facultie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.facultie', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_name',
            field=models.CharField(max_length=45, verbose_name='Имя главы'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='department',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='department',
            name='teachers_count',
            field=models.IntegerField(verbose_name='Количество преподавателей'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='cycle',
            field=models.CharField(max_length=45, verbose_name='Цикл дисциплин'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='hours',
            field=models.IntegerField(verbose_name='Длительность, ч'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='corp_number',
            field=models.CharField(max_length=10, verbose_name='Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='dean_name',
            field=models.CharField(max_length=45, verbose_name='Декан'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='admission_to_work',
            field=models.IntegerField(verbose_name='Год притяния на работу'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth',
            field=models.IntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=45, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVTExample.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=45, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(max_length=45, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
    ]
